### ISSUE TITLE
Extra reading

### ISSUE THREAD

**Issue by antagomir** [microbiome/course_2022_oulu#4]
I got good feedback on chapter 10 here:
https://microbiome.github.io/course_2021_radboud/study-material.html#further-reading

-> Let us make sure that the relevant links are collected in OMA, and then the course website has a clear link to the OMA chapter.

@shigdel are you able to make a PR to OMA and this repository, adding these? Or if all material is there already let us know so we can close this.

**Comment by shigdel** [comment]
where shall i add this one

**Comment by antagomir** [comment]
Can you suggest what would be a good place? Make a suggestion through PR, then we can discuss if something has to be changed. Would this work? Do you know how to render and view the book locally on your own system before pushing to github?

**Comment by shigdel** [comment]
i tried but not able to render the whole document can you please let me
know how to do that

**Comment by antagomir** [comment]
If you have a technical problem it is best if you ask specifically in Slack and describe the problem.

**Comment by shigdel** [comment]
it worked fine I tried  it with Tuomas

**Comment by antagomir** [comment]
Great.  Looking fwd to the PR.

**Comment by TuomasBorman** [comment]
See commit c5fc87e22ec0867fcd7064a310dbed748651d99a

**Comment by shigdel** [comment]
***@***.***
